[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"

# Supabase environment variables will be set in the Netlify dashboard
# Don't include actual keys in this file

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 